[package]
name = "librakaly"
version = "0.9.1"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2018"
repository = "https://github.com/rakaly/librakaly.git"
description = "A C wrapper around rakaly functionality"
readme = "README.md"
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]
name = "rakaly"

[dependencies]
libc = "0.2"
eu4save = { version = "0.8", default-features = false, features = ["libdeflate"] }
imperator-save = { version = "0.4", default-features = false, features = ["libdeflate"] }
ck3save = { version = "0.4", default-features = false, features = ["libdeflate"] }
hoi4save = "0.3"
vic3save = { git = "https://github.com/pdx-tools/pdx-tools", features = ["libdeflate"]  }

[build-dependencies]
cbindgen = "0.20"
