name: ci
on:
  push:
  schedule:
  - cron: '00 01 * * *'

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build:
        - linux
        - macos
        - win-msvc
        include:
        - build: linux
          os: ubuntu-latest
        - build: macos
          os: macos-latest
        - build: win-msvc
          os: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache saves
      uses: actions/cache@v2
      with:
        path: verifier/assets/saves
        key: verifier/assets/saves
    - name: Decrypt tokens
      run: ./assets/ci/decrypt_secret.sh
      shell: bash
      env:
        TOKEN_PASSPHRASE: ${{ secrets.TOKEN_PASSPHRASE }}
    - name: Set cargo environment variables
      shell: bash
      run: |
        echo "EU4_IRONMAN_TOKENS=$current_dir/assets/tokens/eu4.txt" >> $GITHUB_ENV
        echo "CK3_IRONMAN_TOKENS=$current_dir/assets/tokens/ck3.txt" >> $GITHUB_ENV
        echo "IMPERATOR_TOKENS=$current_dir/assets/tokens/imperator.txt" >> $GITHUB_ENV
      env:
        current_dir: ${{ github.workspace }}
    - name: Build
      run: cargo build --all --verbose
    - name: GCC can build
      if: matrix.os == 'ubuntu-latest'
      working-directory: ./target
      run: |
        set -eou
        cp ../sample.c .
        cp ../sample.cpp .
        cp ../rakaly_wrapper.h .
        cp ./debug/librakaly.so .
        gcc sample.c -o melter -Werror -Wall -Wextra -O3 librakaly.so
        clang++ sample.cpp -o meltercpp -Werror -Wall -Wextra -std=c++17 librakaly.so
    - name: Run verifier
      working-directory: ./verifier
      shell: bash
      run: |
        set -eou
        cp -r ../target/debug/*rakaly* .
        cargo build --release
        cargo run --release -- --game eu4 > /dev/null
        cargo run --release -- --game ck3 > /dev/null
        cargo run --release -- --game imperator > /dev/null
      env:
        LD_LIBRARY_PATH: '.'
