name: ci
on:
  push:
  schedule:
  - cron: '00 01 * * *'

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build:
        - linux
        - macos
        - win-msvc
        include:
        - build: linux
          os: ubuntu-latest
        - build: macos
          os: macos-latest
        - build: win-msvc
          os: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache saves
      uses: actions/cache@v3
      with:
        path: assets/saves
        key: assets/saves
    - name: Decrypt tokens
      run: ./assets/ci/decrypt_secret.sh
      shell: bash
      env:
        TOKEN_PASSPHRASE: ${{ secrets.TOKEN_PASSPHRASE }}
    - name: Set cargo environment variables
      shell: bash
      run: |
        echo "EU4_IRONMAN_TOKENS=$current_dir/assets/tokens/eu4.txt" >> $GITHUB_ENV
        echo "CK3_IRONMAN_TOKENS=$current_dir/assets/tokens/ck3.txt" >> $GITHUB_ENV
        echo "IMPERATOR_TOKENS=$current_dir/assets/tokens/imperator.txt" >> $GITHUB_ENV
        echo "HOI4_IRONMAN_TOKENS=$current_dir/assets/tokens/hoi4.txt" >> $GITHUB_ENV
        echo "VIC3_IRONMAN_TOKENS=$current_dir/assets/tokens/vic3.txt" >> $GITHUB_ENV
      env:
        current_dir: ${{ github.workspace }}
    - name: Build
      run: cargo build --all --verbose --release
    - name: create save assets directory
      shell: bash
      run: mkdir -p assets/saves
    - name: Retrieve assets
      shell: bash
      run: |
        [ ! -f kandy2.bin.eu4 ] && curl -O https://eu4saves-test-cases.s3.us-west-002.backblazeb2.com/kandy2.bin.eu4 || true
        [ ! -f af_Munso_867_Ironman.ck3 ] && curl -O https://ck3saves-test-cases.s3.us-west-002.backblazeb2.com/af_Munso_867_Ironman.ck3 || true
        [ ! -f observer1.5.rome ] && curl -O https://imperator-test-cases.s3.us-west-002.backblazeb2.com/observer1.5.rome || true
        [ ! -f 1.10-ironman.zip ] && curl -O https://hoi4saves-test-cases.s3.us-west-002.backblazeb2.com/1.10-ironman.zip && unzip 1.10-ironman.zip || true
      working-directory: ./assets/saves
    - name: Run verifier
      if: matrix.os == 'ubuntu-latest'
      working-directory: ./target
      run: |
        set -eou
        cp ../sample.cpp .
        cp ./release/librakaly.so .

        g++ sample.cpp -o melter -std=c++17 -Werror -Wall -Wextra -O2 librakaly.so
        LD_LIBRARY_PATH=. ./melter save ../assets/saves/kandy2.bin.eu4 > /dev/null
        LD_LIBRARY_PATH=. ./melter save ../assets/saves/af_Munso_867_Ironman.ck3 > /dev/null
        LD_LIBRARY_PATH=. ./melter save ../assets/saves/observer1.5.rome > /dev/null
        LD_LIBRARY_PATH=. ./melter save ../assets/saves/1.10-ironman.hoi4 > /dev/null
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Run verifier (windows)
      if: matrix.os == 'windows-latest'
      working-directory: ./target
      run: |
        cp ..\sample.cpp .
        cp .\release\rakaly* .

        cl /EHsc sample.cpp /std:c++17 /link rakaly.dll.lib /out:melter.exe
        .\melter.exe save ..\assets\saves\kandy2.bin.eu4 > NUL
        .\melter.exe save ..\assets\saves\af_Munso_867_Ironman.ck3 > NUL
        .\melter.exe save ..\assets\saves\observer1.5.rome > NUL
        .\melter.exe save ..\assets\saves\1.10-ironman.hoi4 > NUL
